[package]
name = "inliner"
version = "0.1.0"
authors = ["Jack Mordaunt <jackmordaunt@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
pretty_assertions = "0.6.1"
mime_guess = "2.0.1"
clap = "2.33.0"
